=== pcdelacr/Prime13_fuse_test_methods/ArrayReadFuse/temp/packages/prime.businesslogic.mbist/13.3.7.4/content/schemas/RecoveryJson.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "RecoveryJson",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "Version": {
      "type": "number",
      "format": "double"
    },
    "RecoveryToken": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ValidOptions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "RecoveryPriority": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Int32OrString"
      }
    },
    "ErrorValue": {
      "type": "string"
    },
    "FailValue": {
      "type": "string"
    },
    "PassValue": {
      "type": "string"
    },
    "DesignIps": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/RecoveryIpsJson"
      }
    }
  },
  "definitions": {
    "RecoveryIpsJson": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Type": {
          "$ref": "#/definitions/RecoveryIpTypes"
        },
        "Required": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "RecoveryOptions": {
          "type": "object",
          "additionalProperties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "RecoveryIpTypes": {
      "type": "string",
      "enum": [
        "Partial",
        "Full"
      ]
    },
    "Int32OrString": {
      "oneOf": [
        {
          "type": "integer",
          "format": "int32"
        },
        {
          "type": "string",
          "pattern": "^[+-]?\\d+$"
        }
      ]
    }
  }
}

=== pcdelacr/Prime13_fuse_test_methods/PortControlTEM/temp/packages/prime.testmethods.mbist/13.3.7.4/contentFiles/any/any/__ReferencedDocs/.attachments/Recovery.json
{
  "Version": 1.0,
  "RecoveryToken": [ "IPU2", "IPU3" ],
  "ValidOptions": [ "0,2", "0,3", "1,023" ],
  "RecoveryPriority": [ 1, 2, 3 ],
  "ErrorValue": "9",
  "FailValue": "1",
  "PassValue": "0",
  "DesignIps": {
    "IPU2": {
      "Type": "Full",
      "Required": [],
      "RecoveryOptions": {
        "1": [ "LEHP_BP35_WBP0_MEM2" ]
      }
    },
    "IPU3": {
      "Type": "Partial",
      "Required": [ "LEHP_BP34_WBP0_MEM2" ],
      "RecoveryOptions": {
        "2": [ "LEHP_BP34_WBP0_MEM1" ],
        "3": [ "LEHP_BP34_WBP0_MEM3" ]
      }
    }
  }
}
